[firebase]
FIREBASE_API_KEY = "AIzaSyDUdttY89xF6y62aXAxWS0NmsZ35kzJPtE"
FIREBASE_AUTH_DOMAIN = "guardian-gesture.firebaseapp.com"
FIREBASE_PROJECT_ID = "guardian-gesture"
FIREBASE_STORAGE_BUCKET = "guardian-gesture.appspot.com"
FIREBASE_MESSAGING_SENDER_ID = "503802348568"
FIREBASE_APP_ID = "1:503802348568:web:e75129179e7735369aaf6d"
FIREBASE_DATABASE_URL = "https://guardian-gesture-default-rtdb.firebaseio.com"
